version: "3"
services:
  stasmodels:
    container_name: stasmodels
    image: stasmodels:1.0
    build:
      context: ./docker
      dockerfile: ./stasmodels/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
