version: "3"
services:
  scalecast:
    container_name: scalecast
    image: scalecast:1.0
    build:
      context: ./docker
      dockerfile: ./scalecast/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
