version: "3"
services:
  pykalman:
    container_name: pykalman
    image: pykalman:1.0
    build:
      context: ./docker
      dockerfile: ./pykalman/Dockerfile
      args:
        user_name: ${user_name}
        user_email: ${user_email}
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
