name: Lint                                                  # ワークフロー名。自由に決めてよい

on:                                                         # ワークフローの実行タイミングを指定する
  push:

jobs:                                                       # ワークフローは1つ以上のジョブから成る。ジョブは`jobs`の下で定義される
  run-lint:                                                 # このワークフローのジョブは、`run-lint`ひとつだけである。
    name: Run lint                                          # `name`: ジョブ名
    runs-on: ubuntu-latest                                  # `runs-on`: 実行環境の指定
    timeout-minutes: 5                                      # `timeout-minutes`: 指定した時間でジョブがタイムアウトする
    steps:                                                  # ジョブはステップによって構成される。ステップは`steps`の下で定義される
      - uses: actions/checkout@v2                           # ブランチにチェックアウトする
      - name: Set up Python ${{ matrix.python-version }}    # 最新版のPythonをセットアップする
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install linters                               # linterをインストールする
        run: |                                              # `run`の下にシェルコマンドで処理を記述する
          pip install --upgrade pip
          pip install black isort flake8 nbqa --quiet
      - name: Run lint                                      # lintする
        run: |                                              # `run`の下にシェルコマンドで処理を記述する
          black . --line-length=88
          isort . --profile black
          flake8 . --ignore=E203,E266,E402,E501,E731,F401,F403,F541,F821,W503 \
          --max-line-length=88 --max-complexity=18 --select=B,C,E,F,W,T4,B9
          
          nbqa black . --line-length=88
          nbqa isort .
          nbqa flake8 . --ignore=B008,E203,E265,E266,E402,E501,E731,F401,F403,F541,F811,F821,W503 \
          --max-line-length=88 --max-complexity=18 --select=B,C,E,F,W,T4,B9